### ISSUE TITLE
Unable to properly stop server with this mod

### ISSUE THREAD

**Issue by Johnnybyzhang** [lukasabbe/CustomMotd#2]
I have ran into a issue where the `stop` command cannot stop the server even with this mod in its default configuration.
        - carpet 1.4.147+v240613
        - carpet-extra 1.4.148
        - carpet-tis-addition 1.63.1
           \-- conditional-mixin 0.6.2
        - collective 7.84
        - custommotd 1.1
           \-- org_yaml_snakeyaml 2.2
        - fabric-api 0.103.0+1.21.1
           |-- fabric-api-base 0.4.42+6573ed8c19
           |-- fabric-api-lookup-api-v1 1.6.68+b559734419
           |-- fabric-biome-api-v1 13.0.29+5bd9f1bc19
           |-- fabric-block-api-v1 1.0.22+0af3f5a719
           |-- fabric-block-view-api-v2 1.0.10+6573ed8c19
           |-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a719
           |-- fabric-client-tags-api-v1 1.1.15+6573ed8c19
           |-- fabric-command-api-v1 1.2.49+f71b366f19
           |-- fabric-command-api-v2 2.2.28+6ced4dd919
           |-- fabric-commands-v0 0.2.66+df3654b319
           |-- fabric-content-registries-v0 8.0.16+b559734419
           |-- fabric-convention-tags-v1 2.0.21+7f945d5b19
           |-- fabric-convention-tags-v2 2.6.1+9b16164119
           |-- fabric-crash-report-info-v1 0.2.29+0af3f5a719
           |-- fabric-data-attachment-api-v1 1.1.28+1daea21519
           |-- fabric-data-generation-api-v1 20.2.18+16c4ae2519
           |-- fabric-dimensions-v1 4.0.0+6fc22b9919
           |-- fabric-entity-events-v1 1.7.0+2122d82819
           |-- fabric-events-interaction-v0 0.7.12+ba9dae0619
           |-- fabric-game-rule-api-v1 1.0.53+6ced4dd919
           |-- fabric-item-api-v1 11.0.0+afdfc92119
           |-- fabric-item-group-api-v1 4.1.5+3fc0e55219
           |-- fabric-key-binding-api-v1 1.0.47+0af3f5a719
           |-- fabric-keybindings-v0 0.2.45+df3654b319
           |-- fabric-lifecycle-events-v1 2.3.12+6c1df36019
           |-- fabric-loot-api-v2 3.0.14+3f89f5a519
           |-- fabric-loot-api-v3 1.0.2+3f89f5a519
           |-- fabric-message-api-v1 6.0.13+6573ed8c19
           |-- fabric-model-loading-api-v1 2.0.0+fe474d6b19
           |-- fabric-networking-api-v1 4.2.2+60c3209b19
           |-- fabric-object-builder-api-v1 15.2.0+40875a9319
           |-- fabric-particles-v1 4.0.2+6573ed8c19
           |-- fabric-recipe-api-v1 5.0.12+6508971219
           |-- fabric-registry-sync-v0 5.1.2+60c3209b19
           |-- fabric-renderer-api-v1 3.4.0+c705a49c19
           |-- fabric-renderer-indigo 1.7.0+c705a49c19
           |-- fabric-renderer-registries-v1 3.2.68+df3654b319
           |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2e19
           |-- fabric-rendering-fluids-v1 3.1.6+1daea21519
           |-- fabric-rendering-v0 1.1.71+df3654b319
           |-- fabric-rendering-v1 5.0.5+df16efd019
           |-- fabric-resource-conditions-api-v1 4.3.0+8dc279b119
           |-- fabric-resource-loader-v0 1.3.0+5659912919
           |-- fabric-screen-api-v1 2.0.25+8b68f1c719
           |-- fabric-screen-handler-api-v1 1.3.86+b559734419
           |-- fabric-sound-api-v1 1.0.23+6573ed8c19
           |-- fabric-transfer-api-v1 5.1.17+1db1cc1f19
           \-- fabric-transitive-access-wideners-v1 6.1.0+1daea21519
        - fabricloader 0.16.4
           \-- mixinextras 0.4.1
        - java 21
        - luckperms 5.4.141
           \-- fabric-permissions-api-v0 0.3.1
        - minecraft 1.21.1
        - modernfix 5.19.3+mc1.21.1
        - placeholder-api 2.4.1+1.21
        - servux 0.3.7
           \-- fabric-permissions-api-v0 0.3.1
        - skinrestorer 2.0.3+1.21
        - syncmatica 0.3.12-sakura.6
        - teleport_commands 1.1.2
        - voicechat 1.21.1-2.5.21
           \-- fabric-key-binding-api-v1 1.0.47+0af3f5a76a
        - welcomemessage 2.6
        - worldedit 7.3.6+6892-3d660b8
I can fix this issue by removing CustomMotd
Is there anything I can do to resolve this issue?

**Comment by lukasabbe** [comment]
Will look at it

**Comment by lukasabbe** [comment]
I know what the problem is, let me fix it
