### ISSUE TITLE
[Bug] Exception in server tick loop: Setting only a number/interger in the player list causes it to crash

### ISSUE THREAD

**Issue by zndrmn** [lukasabbe/CustomMotd#6]
```
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
```

Here's my player list config, I assume this is also an issue with the MOTD config as well.
```yml
#Hover text for player amount, max 6, (Only visual)
plyer-list:
  - 1
```
Also does "max 6" mean you can only have 6 lines or a max of 6 Placeholders from the Placeholder API?

**Comment by lukasabbe** [comment]
It means 6 max lines, i will fix this bug when I have time :=).
You can always have "1" I think, if you need it now

**Comment by zndrmn** [comment]
When I was testing things out I was able to go past 6 lines, I think I got up to like 15 or 12 lines (which I think 12 should be the max) and that's actually how I found this bug out.
That's why I was kinda confused about the 6 lines thing.

**Comment by lukasabbe** [comment]
Hmm, what, I thought it just said ..and x more.
But I might have understood the code wrong haha. Will take a look at that too ;)
