### ISSUE TITLE
[Feature] Simplified Text Format support from Placeholder API (colored text & decorations)

### ISSUE THREAD

**Issue by zndrmn** [lukasabbe/CustomMotd#7]
Since there's already support for placeholders in Placeholder API, I think it would also be pretty neat if there was also an implementation of the Simplified Text Format (from Placeholder API). That way we can have custom gradients, colors, and placeholders to customize the MOTD and Player list with!

**Comment by lukasabbe** [comment]
Sounds like a good feature. I will take a look at it after my exam period.
